# Generated by Django 3.2 on 2021-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('cin', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
